server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
            - Path=/api/roles/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/invoices/**